filebeat.modules:
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true
- module: auditd
  log:
    enabled: true

#========================== Filebeat autodiscover ==============================
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.logstash:
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]

#============================== Dashboards =====================================
setup.dashboards:
  enabled: false

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: ${KIBANA_USERNAME}
  password: ${KIBANA_PASSWORD}

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: false
  elasticsearch:
