{
 "title": "PGPool2",
 "description": "Dashboard for https://github.com/pgpool/pgpool2_exporter",
 "tags": [
  "pgpool",
  "database",
  "postgres"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(pgpool2_pool_nodes_status{}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Databases",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pgpool2_pool_nodes_status{}) by (hostname, role)",
     "legendFormat": "{{ hostname }} - {{ role }}"
    }
   ]
  },
  {
   "title": "ERROR Count",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "irate(pgpool2_last_scrape_error{}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Replication Delay",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "irate(pgpool2_pool_nodes_replication_delay{hostname=~\"$node\"}[1m])",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pgpool2_backend_by_process_used) by (database)",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "SELECT Statement Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(pgpool2_pool_nodes_select_cnt{hostname=~\"$node\"}[1m])",
     "legendFormat": "{{ hostname }}"
    }
   ]
  }
 ]
}