{
 "title": "Zabbix-Cluster",
 "tags": [
  "zabbix",
  "prometheus",
  "postgres"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HAProxy",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " up{instance=~\"^http://haproxy.+\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{host_group=\"pg\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DB Active Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pgpool2_backend_by_process_used) by (database)",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Zabbix fontend web servers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"^http://zabbix-web.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zabbix backend servers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{host_group=\"zabbix-server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SELECT Statement Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "irate(pgpool2_pool_nodes_select_cnt{hostname=~\"pg-\\\\d+\"}[1m])",
     "legendFormat": "{{ hostname }}"
    }
   ]
  }
 ]
}