heartbeat.monitors:

- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: ["filebeat","metricbeat","kibana","es01","es02","es03"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  wait: 1s

- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://otus.ru"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response.status: [200, 301]

- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://google.com"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response.status: [200, 301]

processors:
- add_docker_metadata: ~

monitoring.enabled: false

#========================== Elasticsearch output ===============================
output.logstash:
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]

logging.to_files: false
